config/routes.rb
Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  get '/locale/:locale', to: 'dashboards#locale', as: :locale
  resources :gifts, exept: [:show]
  resources :users, only: [:show, :index]

  resources :organisations, only: [:show, :index]

  get '/mergers', to: 'users#mergers', as: :mergers
  get 'users/:id', to: 'users#show'
  get '/users/unsubscribe/:token', to: 'users#unsubscribe', as: :user_unsubscribe

  resources :events

  resources :projects do
    collection do
      get :autofill
      post :claim
    end
    member do
      put reactivate
    end
  end

  resources :contributions do
    collections do
        get :meta
    end
  end

  resources :pull_request, only: [:index], conttroller: 'contributions' do
    collection do
      get :meta
    end
  end

  resource :dashboard, only: [:show, :destroy] do
    member do
      get :delete
      delete :destroy
    end
  end
  resource :pull_request_download, only: :create

  get '/resend_confirmation', to: 'dashboards#resend_confirmation_email', as: 'resend_confirmation'
  get '/confirm/:confirmation_token', to: 'dasboards#confirm_email', as: 'confirm_email'

  get '/preferences', to: 'dashboards#preferences', as: 'preferences'
  patch '/preferences/update', to: 'dashboards#update_preferences', as: 'update_preferences'
  get :my_suggestions, to: 'users#projects', as: :mysuggestions

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/contributors/map', to: 'contributor_map#show'

  get '/auth/twitter/callback', to: 'twitter#authorize'
  delete '/twitter/remove',     to: 'twitter#remove'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/failure',              to: 'sessions#failure'


  get 'about', to: 'static#about'
  get 'sponsors' => redirect('/about') # old sponsors url
  get 'humans', to: 'static#humans'
  get 'api', to: 'static#api'
  get 'contributing', to: 'static#contributing'
  get '2018', to: 'static#2018'

  get '/unsubscribe', to: 'unsubscribes#new', as: :unsubscribe
  post '/unsubscribe', to: 'unsubscribes#create'

  resources :languages, only: [:show] do
    member do
      get :projects
      get :pull_requests
      get :users
    end
  end

  root to: 'static#homepage'

  get '/email' => redirect('/preferences') # old preferences URL

  get '/:id' => redirect('/users/%{id}') #User public vanity url, must be lowest priority

  namespace :admin do
    post '/dasher', to: 'dasher#new_pull_request'
    resources :projects, only: [:index, :edit, :update, :destroy]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :name, :location, :url, :start_time, :description, presence: true
  validates :url, format: URI::Parser.new.make_regexp(%w(http https))
  validate :validate_start_time_is_in_range, if: :start_time
  validate :validate_start_time_is_not_in_the_past, if: :start_time

  def formmated_date
    start_time.strftime('%A %d %B %Y at %I:%M%p')
  end

  def can_edit?(user)
    return false unless user.present?
    user_id == user.id || user.admin?
  end

  def validate_start_time_is_in_range
    errors.add(:start_time, :not_in_range) unless (Time.parse('1st December')..Time.parse('25th December')).cover?(start_time)
  end

  def validate_start_time_is_not_in_the_past
    erros.add(:start_time, :in_past) unless start_time >= Time.zone.now.beginning_of_day
  end
end

app/controllers/events_controller.rb
class Events_controller < ApplicationController
  before_action :ensure_logged_in, except: [:index, :show]

  def index
    @upcoming_events = Event.where(['start_time>= ?', Time.zone.today]).order('start_time')
    @past_events = Event.where(['start_time < ?', Time.zone.today]).order('start_time DESC')
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def edit
    @event = current_user.events.find(params[:id])
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy!
    redirect_to events_path, notice: t('events.notice.destroy_succes')
  end

  def update
    @event = current_user.events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: t('events.notice.edit_success')
    else
      render :edit
    end
  end

  protected

  def event_params
    params(:event).permit(:name, :location, :url, :start_time, :description, :latitude, :longitude)
  end
end

app/views/events/_event.html.erb
<div class="event-item">
  <h2>
    <%= link_to event.name, event %>
  </h2>
  <small>
    <%= octicon "location" %>
    <%= event.location %>
    <br/>
    <%= oction "clock" %>
    <%= event.formatted_date %>
  </small>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event, wrapper: :bootstrap3_horizontal, defaults: {right_column_html: {class: "col-lg-3 col-md-3"}, label_html: {class: "col-lg-2 col-md-2"} }, :html => {:class => 'form-horizontal', :role => "form"} do |form| %>
  <%= form.input :name, label: t("events.new.form.name"), placeholder: t("events.new.form.name_placeholder") %>
  <%= form.input :description, label: t("events.new.form.description"), placeholder: t("events.new.form.description_placeholder") %>
  <%= form.input :location, label: t("events.new.form.location"), placeholder: t("events.new.form.location_placeholder") %>
  <%= form.input :url, label: t("events.new.form.url"), placeholder: t("events.new.form.url_place_holder") %>
  <%= form.input :start_time, label: t("events.new.form.start_time"), as: :string, input_html: {class: "js-datetimepicker"} %>
  <div class="form-group">
    <label class="col-sm-2 control-label">
      <%= t("events.new.form.map") %>
    </label>
    <div class="col-sm-10 col-md-6">
      <div class="map map--small" data-map-picker="true"></div>
      <div class="js-pins">
        <span class="pin"></span>
      </div>
      <%= form.hidden_field :latitude, class: "form-control", step: "any" %>
      <%= form.hidden_field :longitude, class: "form-control", step: "any" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10 col-md-4">
      <%= form.submit t("events.save_event"), class: "btn btn-default" %>
    </div>
  </div>
<% end%>

app/views/events/edit.html.erb
<h3>
  <%= t("events.edit.title") %>
</h3>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="title-block">
  <h2 class="block-title">
    <%= t("events.title") %>
  </h2>
  <p>
    <%= t("events.details") %>
  </p>
  <%= link_to t("events.index.host_an_event"), new_event_path, class: 'btn btn-default' %>
</div>
<% if @upcoming_events.empty? %>
  <h4>
    <i>
      <%= t("events.index.no_upcoming_events") %>
      <%= t("events.index.host_an_event"), new_event_path %>
    </i>
  </h4>
<% else %>
  <div class="row">
    <div class="col-md-6">
      <hr/>
      <div class="map"></div>
      <div class="js-pins">
        <% @upcoming_events.each do |event| %>
          <%= link_to "", event, class: "pin", data: { latitude: event.latitude, longitude: event.longitude } %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-12 col-md-6">
      <%= render @upcoming_events %>
    </div>
  </div>
<% end %>
<% unless @past_events.empty? %>
  <hr/>
  <div class="now">
    <p>
      <button class="btn btn-default toggle-past-events">
        <span>
          <%= t("events.index.show_past_24_pull_requests_events") %>
        </span>
      </button>
    </p>
  </div>
  <div class="row past-events hidden">
    <h4>
      <%= t("events.index.past_24_pull_requests_events") %>
    </h4>
    <div class="col-md-12">
      <%= render @past_events %>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<h3>
  <%= t("events.new.title") %>
</h3>
<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6">
    <div class="map" data-latitude="<%= @event.latitude%>" data-longitude="<%= @event.longitude %>" ></div>
    <div class="js-pins">
      <span class="pin" data-latitude="<%= @event.latitude%>" data-longitude="<%= @event.longitude %>"></span>
    </div>
  </div>
  <div  class="col-sm-12 col-md-6">
    <h1>
      <%= @event.name %>
      <br/>
      <small>
        <%= @event.location %>
      </small>
      <br/>
      <small>
        <%= @event.formatted_date %>
      </small>
    </h1>
    <hr/>
    <p class="js-emoji">
      <%= @event.description %>
    </p>
    <%= link_to t("events.show.view_event_details"), @event.url, class: "btn btn-primary" %>
    <% if @event.can_edit?(current_user) %>
      <hr/>
      <%= link_to t("events.show.edit_event"), edit_event_path(@event), class: "btn btn-default" %>
      <%= link_to t("events.show.destroy_event"), @event, data: { confirm: I18n.t("events.show.confirm_destroy") }, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>